language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.8

sudo: required
services:
  - docker

before_install:
  - docker pull quay.io/coreos/etcd:v2.2.0
  - docker run -d --net host quay.io/coreos/etcd:v2.2.0
