version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.2.0
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:4001,http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:4001,http://localhost:2379
    ports:
      - "4001:4001"
      - "2379:2379"
