etcd:
  image: gcr.io/google_containers/etcd:2.0.12
  command: >
    /usr/local/bin/etcd
    --addr=127.0.0.1:4001
    --bind-addr=0.0.0.0:4001
    --data-dir=/var/etcd/data
  net: host
master:
  image: gcr.io/google_containers/hyperkube:v1.1.2
  command: >
    /hyperkube kubelet --containerized
    --hostname-override="127.0.0.1"
    --address="0.0.0.0"
    --api-servers=http://localhost:8080
    --config=/etc/kubernetes/manifests
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /dev:/dev
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
  privileged: true
  net: host
  pid: host
service-proxy:
  image: gcr.io/google_containers/hyperkube:v1.1.2
  command: >
    /hyperkube proxy --v=2
    --master=http://127.0.0.1:8080
  privileged: true
  net: host
