apiVersion: v1
kind: ReplicationController
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v2.2.0
        args:
        - -listen-client-urls
        - http://0.0.0.0:2379
        - -advertise-client-urls
        - http://etcd:2379
