apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: cluster-monitor
        image: eu.gcr.io/akka-cluster-gke/akka-cluster-etcd/monitor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CLUSTER_ROLE
          value: frontend
